# 数据库连接
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/try_their?serverTimezone=UTC
    username: root
    password: root

# mybatis
mybatis:
  type-aliases-package: com.try_their.try_their_project.entity
  mapper-locations: classpath:mapper/*Mapper.xml
# pageHelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
